services:
  postgres:
    image: postgres:15-alpine
    container_name: artisell_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - artisell-net

  loader:
    build: .
    container_name: artisell_loader
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres
    networks:
      - artisell-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: artisell_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD} 
    ports:
      - "5080:80"
    depends_on:
      - postgres
    networks:
      - artisell-net

volumes:
  postgres-data:

networks:
  artisell-net:
    driver: bridge  